@startuml

start
if (Transmit Callenge to be\nSigned from the tag) then (error)
  #pink:Tag is not authentic;
  end
else
  :Receive Challenge Signature;
endif

:Recover Address from Signature;

if (Query certificate from Blockchain\nfor the Recovered Address) then (not found)
  #pink:Product is not authentic;
  end
else
  #palegreen:Product is authentic;
endif

stop
@enduml
